// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetUmbracoUmbracoextensionsApiV1GetMessageError, GetUmbracoUmbracoextensionsApiV1GetMessageResponse } from './types.gen';

export const client = createClient(createConfig());

export const getUmbracoUmbracoextensionsApiV1GetMessage = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUmbracoUmbracoextensionsApiV1GetMessageResponse, GetUmbracoUmbracoextensionsApiV1GetMessageError, ThrowOnError>({
        ...options,
        url: '/umbraco/umbracoextensions/api/v1/getMessage'
    });
};