// This file is auto-generated by @hey-api/openapi-ts

export type GetUmbracoUmbracoextensionsApiV1GetMessageResponse = (string);

export type GetUmbracoUmbracoextensionsApiV1GetMessageError = (unknown);